# Generated by Django 6.0.3 on 2026-04-23 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('FCFA', 'FCFA — CFA Franc'), ('$', 'USD — US Dollar'), ('€', 'EUR — Euro'), ('£', 'GBP — British Pound'), ('₦', 'NGN — Nigerian Naira'), ('KSh', 'KES — Kenyan Shilling'), ('R', 'ZAR — South African Rand'), ('GH₵', 'GHS — Ghanaian Cedi'), ('¥', 'JPY — Japanese Yen'), ('₹', 'INR — Indian Rupee'), ('C$', 'CAD — Canadian Dollar'), ('A$', 'AUD — Australian Dollar')], default='FCFA', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
