# Generated by Django 6.0.3 on 2026-05-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(default='#00ff88', max_length=30),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(default='📦', max_length=20),
        ),
    ]
